spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-drop-mysql.sql
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:3306/batch_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
